/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGPHP
#define SWIGPHP
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2
#define SWIG_POINTER_NO_NULL       0x4

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows returning the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
#define SWIG_ERROR                 (-1)
#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(const swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



/* -----------------------------------------------------------------------------
 * phprun.swg
 *
 * PHP runtime library
 * ----------------------------------------------------------------------------- */

#define swig_owntype                                    int

#ifdef __cplusplus
extern "C" {
#endif

#include "php.h"

#if PHP_MAJOR_VERSION < 7
# error These bindings need PHP 7 or later - to generate PHP5 bindings use: SWIG < 4.0.0 and swig -php5
#endif

#include "zend_inheritance.h"
#include "zend_exceptions.h"
#include "zend_inheritance.h"

#if PHP_MAJOR_VERSION == 7
/* These macros were new in PHP 8.0.  For PHP 7.x we define them to give the
 * same result except without any type declarations.  PHP 7.x supports type
 * declarations, but not for the return type, and alternate types aren't
 * supported, so we don't try to support these.
 */
# define ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(name, byref, num_req, classes, types) \
    ZEND_BEGIN_ARG_INFO_EX(name, 0, byref, num_req)
# define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(name, byref, num_req, types) \
    ZEND_BEGIN_ARG_INFO_EX(name, 0, byref, num_req)

/* NB We can just ignore `default` here we currently always pass NULL for it
 * (this mechanism for specifying default parameter values was new in PHP 8.0
 * so it's not useful while we still want to support PHP7 too).
 */
# define ZEND_ARG_OBJ_TYPE_MASK(byref, name, classes, types, default) \
    ZEND_ARG_INFO(byref, name)
# define ZEND_ARG_TYPE_MASK(byref, name, types, default) \
    ZEND_ARG_INFO(byref, name)
#endif

#include <stdlib.h> /* for abort(), used in generated code. */

#define SWIG_BOOL_CONSTANT(N, V) REGISTER_BOOL_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_LONG_CONSTANT(N, V) REGISTER_LONG_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_DOUBLE_CONSTANT(N, V) REGISTER_DOUBLE_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_STRING_CONSTANT(N, V) REGISTER_STRING_CONSTANT(#N, (char*)V, CONST_CS | CONST_PERSISTENT)
#define SWIG_CHAR_CONSTANT(N, V) do {\
    char swig_char = (V);\
    REGISTER_STRINGL_CONSTANT(#N, &swig_char, 1, CONST_CS | CONST_PERSISTENT);\
} while (0)

/* ZEND_CONSTANT_SET_FLAGS was new in PHP 7.3. */
#ifdef ZEND_CONSTANT_SET_FLAGS
# define SWIG_ZEND_CONSTANT_SET_FLAGS ZEND_CONSTANT_SET_FLAGS
#else
# define SWIG_ZEND_CONSTANT_SET_FLAGS(C, F, N) do { (C)->flags = (F); (C)->module_number = (N); } while (0)
#endif

/* zend_object_alloc was new in PHP 7.3. */
#if PHP_MAJOR_VERSION == 7 && PHP_MINOR_VERSION < 3
static zend_always_inline void *zend_object_alloc(size_t obj_size, zend_class_entry *ce) {
    void *obj = emalloc(obj_size + zend_object_properties_size(ce));
    memset(obj, 0, obj_size - sizeof(zval));
    return obj;
}
#endif

/* ZEND_THIS was new in PHP 7.4. */
#ifndef ZEND_THIS
# define ZEND_THIS &EX(This)
#endif

#ifdef __cplusplus
}
#endif

#define SWIG_fail goto fail

static const char *default_error_msg = "Unknown error occurred";
static int default_error_code = E_ERROR;

#define SWIG_PHP_Arg_Error_Msg(argnum,extramsg) "Error in argument " #argnum " "#extramsg

#define SWIG_PHP_Error(code,msg) do { zend_throw_exception(NULL, msg, code); SWIG_fail; } while (0)

#define SWIG_contract_assert(expr,msg) \
  do { if (!(expr)) zend_printf("Contract Assert Failed %s\n", msg); } while (0)

/* Standard SWIG API */
#define SWIG_GetModule(clientdata) SWIG_Php_GetModule()
#define SWIG_SetModule(clientdata, pointer) SWIG_Php_SetModule(pointer, *(int*)clientdata)

static zend_class_entry SWIG_Php_swig_wrapped_interface_ce;

#if PHP_MAJOR_VERSION == 7
/* zend_class_implements_interface() was new in PHP 8.0.
 *
 * We could use instanceof_function_ex(C, I, 1) here for 7.4, but for 7.3
 * and earlier that doesn't work, so instead we just provide a compatibility
 * implementation which does what zend_class_implements_interface() does in 8.x
 * and use that for all 7.x so there are fewer variants to worry about testing.
 */
static int zend_class_implements_interface(const zend_class_entry *class_ce, const zend_class_entry *interface_ce) {
  uint32_t i;
  if (class_ce->num_interfaces) {
    for (i = 0; i < class_ce->num_interfaces; i++) {
      if (class_ce->interfaces[i] == interface_ce) {
	return 1;
      }
    }
  }
  return 0;
}
#endif

/* used to wrap returned objects in so we know whether they are newobject
   and need freeing, or not */
typedef struct {
  void * ptr;
  int newobject;
  const swig_type_info * type;
  zend_object std;
} swig_object_wrapper;

#define SWIG_Z_FETCH_OBJ_P(zv) swig_php_fetch_object(Z_OBJ_P(zv))

static inline
swig_object_wrapper * swig_php_fetch_object(zend_object *obj) {
  return (swig_object_wrapper *)((char *)obj - XtOffsetOf(swig_object_wrapper, std));
}

#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))

static void
SWIG_SetPointerZval(zval *z, void *ptr, swig_type_info *type, int newobject) {
  // Return PHP NULL for a C/C++ NULL pointer.
  if (!ptr) {
    ZVAL_NULL(z);
    return;
  }

  if (!type->clientdata) {
    zend_type_error("Type: %s not registered with zend", type->name);
    return;
  }

  {
    zend_object *obj;
    swig_object_wrapper *value;
    if (Z_TYPE_P(z) == IS_OBJECT) {
      /* The PHP object is already initialised - this is the case when wrapping
       * the return value from a PHP constructor. */
      obj = Z_OBJ_P(z);
    } else {
      zend_class_entry *ce = (zend_class_entry*)(type->clientdata);
      obj = ce->create_object(ce);
      ZVAL_OBJ(z, obj);
    }
    value = swig_php_fetch_object(obj);
    value->ptr = ptr;
    value->newobject = (newobject & 1);
    value->type = type;
  }
}

/* We wrap C/C++ pointers as PHP objects. */
static int
SWIG_ConvertPtrAndOwn(zval *z, void **ptr, swig_type_info *ty, int flags, swig_owntype *own) {
  if (own)
    *own = 0;

  if (z == NULL) {
    *ptr = 0;
    return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
  }

  switch (Z_TYPE_P(z)) {
    case IS_OBJECT: {
      zend_object *obj = Z_OBJ_P(z);
      swig_object_wrapper *value;
      if (ty && ty->clientdata == (void*)obj->ce) {
	// Object is exactly the class asked for - this handles common cases cheaply,
	// and in particular the PHP classes we use to wrap a pointer to a non-class.
      } else if (!zend_class_implements_interface(obj->ce, &SWIG_Php_swig_wrapped_interface_ce)) {
	// Not an object we've wrapped.
	return -1;
      }

      /* convert and cast value->ptr from value->type to ptr as ty. */
      value = swig_php_fetch_object(obj);
      if (!ty) {
	/* They don't care about the target type, so just pass on the pointer! */
	*ptr = value->ptr;
      } else {
	swig_cast_info *tc = SWIG_TypeCheckStruct(value->type, ty);
	if (tc) {
	  int newmemory = 0;
	  *ptr = SWIG_TypeCast(tc, value->ptr, &newmemory);
	  if (newmemory == SWIG_CAST_NEW_MEMORY) {
	    assert(own); /* badly formed typemap which will lead to a memory leak - it must set and use own to delete *ptr */
	    if (own)
	      *own |= SWIG_CAST_NEW_MEMORY;
	  }
	} else {
	  *ptr = NULL;
	}
      }
      if (*ptr == NULL) return SWIG_ERROR;
      if (flags & SWIG_POINTER_DISOWN) {
	value->newobject = 0;
      }
      return SWIG_OK;
    }
    case IS_NULL:
      *ptr = 0;
      return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
  }

  return -1;
}

static int
SWIG_ConvertPtr(zval *z, void **ptr, swig_type_info *ty, int flags) {
  return SWIG_ConvertPtrAndOwn(z, ptr, ty, flags, 0);
}

static const char const_name[] = "swig_runtime_data_type_pointer";
static swig_module_info *SWIG_Php_GetModule(void) {
  zval *pointer = zend_get_constant_str(const_name, sizeof(const_name) - 1);
  if (pointer) {
    if (Z_TYPE_P(pointer) == IS_LONG) {
      return (swig_module_info *) pointer->value.lval;
    }
  }
  return NULL;
}

static void SWIG_Php_SetModule(swig_module_info *pointer, int module_number) {
  REGISTER_LONG_CONSTANT(const_name, (long) pointer, CONST_CS | CONST_PERSISTENT);
}

/* Common parts of the "create_object" object handler. */
static zend_object *SWIG_Php_do_create_object(zend_class_entry *ce, zend_object_handlers *handlers) {
  swig_object_wrapper *obj = (swig_object_wrapper*)zend_object_alloc(sizeof(swig_object_wrapper), ce);
  zend_object_std_init(&obj->std, ce);
  object_properties_init(&obj->std, ce);
  obj->std.handlers = handlers;
  obj->newobject = 1;
  return &obj->std;
}

/* Common parts of the "free_obj" object handler.
   Returns void* pointer if the C/C++ object should be destroyed. */
static void* SWIG_Php_free_obj(zend_object *object) {
  if (object) {
    swig_object_wrapper *obj = swig_php_fetch_object(object);
    zend_object_std_dtor(&obj->std);
    if (obj->newobject) return obj->ptr;
  }
  return NULL;
}


/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_p_unsigned_char swig_types[0]
#define SWIGTYPE_p_unsigned_int swig_types[1]
static swig_type_info *swig_types[3];
static swig_module_info swig_module = {swig_types, 2, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */

/* header section */
#define SWIG_name  "libpcphp"
#ifdef __cplusplus
extern "C" {
#endif
#include "php_ini.h"
#include "ext/standard/info.h"
#include "php_libpcphp.h"
#ifdef __cplusplus
}
#endif



#define SWIG_PHP_INTERFACE_Iterator_CE zend_ce_iterator
#define SWIG_PHP_INTERFACE_Iterator_HEADER "zend_interfaces.h"

#define SWIG_PHP_INTERFACE_IteratorAggregate_CE zend_ce_aggregate
#define SWIG_PHP_INTERFACE_IteratorAggregate_HEADER "zend_interfaces.h"

#define SWIG_PHP_INTERFACE_ArrayAccess_CE zend_ce_arrayaccess
#define SWIG_PHP_INTERFACE_ArrayAccess_HEADER "zend_interfaces.h"

#define SWIG_PHP_INTERFACE_Serializable_CE zend_ce_serializable
#define SWIG_PHP_INTERFACE_Serializable_HEADER "zend_interfaces.h"

#define SWIG_PHP_INTERFACE_Countable_CE zend_ce_countable
#define SWIG_PHP_INTERFACE_Countable_HEADER "zend_interfaces.h"

#define SWIG_PHP_INTERFACE_OuterIterator_CE spl_ce_OuterIterator
#define SWIG_PHP_INTERFACE_OuterIterator_HEADER "ext/spl/spl_iterators.h"

#define SWIG_PHP_INTERFACE_RecursiveIterator_CE spl_ce_RecursiveIterator
#define SWIG_PHP_INTERFACE_RecursiveIterator_HEADER "ext/spl/spl_iterators.h"

#define SWIG_PHP_INTERFACE_SeekableIterator_CE spl_ce_SeekableIterator
#define SWIG_PHP_INTERFACE_SeekableIterator_HEADER "ext/spl/spl_iterators.h"

#define SWIG_PHP_INTERFACE_SplObserver_CE spl_ce_SplObserver
#define SWIG_PHP_INTERFACE_SplObserver_HEADER "ext/spl/spl_observer.h"

#define SWIG_PHP_INTERFACE_SplSubject_CE spl_ce_SplSubject
#define SWIG_PHP_INTERFACE_SplSubject_HEADER "ext/spl/spl_observer.h"

#define SWIG_PHP_INTERFACE_DateTimeInterface_CE php_date_get_interface_ce()
#define SWIG_PHP_INTERFACE_DateTimeInterface_HEADER "ext/date/php_date.h"

// The "json" extension needs to be loaded earlier that us for this to work.
#define SWIG_PHP_INTERFACE_JsonSerializable_CE php_json_serializable_ce
#define SWIG_PHP_INTERFACE_JsonSerializable_HEADER "ext/json/php_json.h"

// New in PHP 8.0.
#if PHP_MAJOR_VERSION >= 8
# define SWIG_PHP_INTERFACE_Stringable_CE zend_ce_stringable
# define SWIG_PHP_INTERFACE_Stringable_HEADER "zend_interfaces.h"
#endif


static zend_class_entry *SWIG_Php_ce_libpcphp;

/* class entry for pointer to _p_unsigned_char */
static zend_class_entry *SWIG_Php_ce__p_unsigned_char;

/* class entry for pointer to _p_unsigned_int */
static zend_class_entry *SWIG_Php_ce__p_unsigned_int;


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_unsigned_int = {"_p_unsigned_int", "unsigned int *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] = {
  &_swigt__p_unsigned_char,
  &_swigt__p_unsigned_int,
};

static swig_cast_info _swigc__p_unsigned_char[] = {  {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_unsigned_int[] = {  {&_swigt__p_unsigned_int, 0, 0, 0},{0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] = {
  _swigc__p_unsigned_char,
  _swigc__p_unsigned_int,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

/* end header section */
/* vdecl subsection */
/* end vdecl subsection */
/* wrapper section */
static PHP_METHOD(libpcphp,PcAPI_initialize) {
  PHP_FN(PcAPI_initialize)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_initialize) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[0])) {
    arg1 = (char *) 0;
  } else {
    convert_to_string(&args[0]);
    arg1 = (char *) Z_STRVAL(args[0]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)PcAPI_initialize(arg1,arg2);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_getSession) {
  PHP_FN(PcAPI_getSession)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_getSession) {
  char *arg1 = (char *) 0 ;
  zval args[1];
  int result;
  
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[0])) {
    arg1 = (char *) 0;
  } else {
    convert_to_string(&args[0]);
    arg1 = (char *) Z_STRVAL(args[0]);
  }
  /*@SWIG@*/;
  
  result = (int)PcAPI_getSession((char const *)arg1);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_encrypt) {
  PHP_FN(PcAPI_encrypt)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_encrypt) {
  int arg1 ;
  long long arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  int arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  unsigned int *arg6 = (unsigned int *) 0 ;
  zval args[6];
  int result;
  
  if(ZEND_NUM_ARGS() != 6 || zend_get_parameters_array_ex(6, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,10,CONVERT_LONG_LONG_IN@*/
  switch (Z_TYPE(args[1])) {
  case IS_DOUBLE:
    arg2 = (long long) Z_DVAL(args[1]);
    break;
    case IS_STRING: {
      char * endptr;
      errno = 0;
      arg2 = (long long) strtoll(Z_STRVAL(args[1]), &endptr, 10);
      if (*endptr == '\0' && !errno) break;
    }
    /* FALL THRU */
  default:
    arg2 = (long long) zval_get_long(&args[1]);
  }
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[2], (void **) &arg3, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 3 of PcAPI_encrypt");
    return;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[4], (void **) &arg5, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 5 of PcAPI_encrypt");
    return;
  }
  
  
  if (SWIG_ConvertPtr(&args[5], (void **) &arg6, SWIGTYPE_p_unsigned_int, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_int for argument 6 of PcAPI_encrypt");
    return;
  }
  
  result = (int)PcAPI_encrypt(arg1,arg2,arg3,arg4,arg5,arg6);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_decrypt) {
  PHP_FN(PcAPI_decrypt)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_decrypt) {
  int arg1 ;
  long long arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  int arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  unsigned int *arg6 = (unsigned int *) 0 ;
  zval args[6];
  int result;
  
  if(ZEND_NUM_ARGS() != 6 || zend_get_parameters_array_ex(6, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,10,CONVERT_LONG_LONG_IN@*/
  switch (Z_TYPE(args[1])) {
  case IS_DOUBLE:
    arg2 = (long long) Z_DVAL(args[1]);
    break;
    case IS_STRING: {
      char * endptr;
      errno = 0;
      arg2 = (long long) strtoll(Z_STRVAL(args[1]), &endptr, 10);
      if (*endptr == '\0' && !errno) break;
    }
    /* FALL THRU */
  default:
    arg2 = (long long) zval_get_long(&args[1]);
  }
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[2], (void **) &arg3, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 3 of PcAPI_decrypt");
    return;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[4], (void **) &arg5, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 5 of PcAPI_decrypt");
    return;
  }
  
  
  if (SWIG_ConvertPtr(&args[5], (void **) &arg6, SWIGTYPE_p_unsigned_int, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_int for argument 6 of PcAPI_decrypt");
    return;
  }
  
  result = (int)PcAPI_decrypt(arg1,arg2,arg3,arg4,arg5,arg6);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_encrypt_name) {
  PHP_FN(PcAPI_encrypt_name)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_encrypt_name) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  int arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  unsigned int *arg6 = (unsigned int *) 0 ;
  zval args[6];
  int result;
  
  if(ZEND_NUM_ARGS() != 6 || zend_get_parameters_array_ex(6, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[2], (void **) &arg3, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 3 of PcAPI_encrypt_name");
    return;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[4], (void **) &arg5, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 5 of PcAPI_encrypt_name");
    return;
  }
  
  
  if (SWIG_ConvertPtr(&args[5], (void **) &arg6, SWIGTYPE_p_unsigned_int, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_int for argument 6 of PcAPI_encrypt_name");
    return;
  }
  
  result = (int)PcAPI_encrypt_name(arg1,(char const *)arg2,arg3,arg4,arg5,arg6);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_decrypt_name) {
  PHP_FN(PcAPI_decrypt_name)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_decrypt_name) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  int arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  unsigned int *arg6 = (unsigned int *) 0 ;
  zval args[6];
  int result;
  
  if(ZEND_NUM_ARGS() != 6 || zend_get_parameters_array_ex(6, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[2], (void **) &arg3, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 3 of PcAPI_decrypt_name");
    return;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  
  if (SWIG_ConvertPtr(&args[4], (void **) &arg5, SWIGTYPE_p_unsigned_char, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_char for argument 5 of PcAPI_decrypt_name");
    return;
  }
  
  
  if (SWIG_ConvertPtr(&args[5], (void **) &arg6, SWIGTYPE_p_unsigned_int, 0) < 0) {
    zend_type_error("Expected SWIGTYPE_p_unsigned_int for argument 6 of PcAPI_decrypt_name");
    return;
  }
  
  result = (int)PcAPI_decrypt_name(arg1,(char const *)arg2,arg3,arg4,arg5,arg6);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_enc_id) {
  PHP_FN(PcAPI_enc_id)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_enc_id) {
  int arg1 ;
  long long arg2 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  zval args[4];
  char *result = 0 ;
  
  if(ZEND_NUM_ARGS() != 4 || zend_get_parameters_array_ex(4, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,10,CONVERT_LONG_LONG_IN@*/
  switch (Z_TYPE(args[1])) {
  case IS_DOUBLE:
    arg2 = (long long) Z_DVAL(args[1]);
    break;
    case IS_STRING: {
      char * endptr;
      errno = 0;
      arg2 = (long long) strtoll(Z_STRVAL(args[1]), &endptr, 10);
      if (*endptr == '\0' && !errno) break;
    }
    /* FALL THRU */
  default:
    arg2 = (long long) zval_get_long(&args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  result = (char *)PcAPI_enc_id(arg1,arg2,arg3,arg4);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_dec_id) {
  PHP_FN(PcAPI_dec_id)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_dec_id) {
  int arg1 ;
  long long arg2 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  zval args[4];
  char *result = 0 ;
  
  if(ZEND_NUM_ARGS() != 4 || zend_get_parameters_array_ex(4, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,10,CONVERT_LONG_LONG_IN@*/
  switch (Z_TYPE(args[1])) {
  case IS_DOUBLE:
    arg2 = (long long) Z_DVAL(args[1]);
    break;
    case IS_STRING: {
      char * endptr;
      errno = 0;
      arg2 = (long long) strtoll(Z_STRVAL(args[1]), &endptr, 10);
      if (*endptr == '\0' && !errno) break;
    }
    /* FALL THRU */
  default:
    arg2 = (long long) zval_get_long(&args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  result = (char *)PcAPI_dec_id(arg1,arg2,arg3,arg4);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_enc_nm) {
  PHP_FN(PcAPI_enc_nm)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_enc_nm) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  zval args[4];
  char *result = 0 ;
  
  if(ZEND_NUM_ARGS() != 4 || zend_get_parameters_array_ex(4, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  result = (char *)PcAPI_enc_nm(arg1,(char const *)arg2,arg3,arg4);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_dec_nm) {
  PHP_FN(PcAPI_dec_nm)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_dec_nm) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  zval args[4];
  char *result = 0 ;
  
  if(ZEND_NUM_ARGS() != 4 || zend_get_parameters_array_ex(4, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg4 = (int) zval_get_long(&args[3]);
  /*@SWIG@*/;
  
  result = (char *)PcAPI_dec_nm(arg1,(char const *)arg2,arg3,arg4);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_cryptFile) {
  PHP_FN(PcAPI_cryptFile)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_cryptFile) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  zval args[4];
  int result;
  
  if(ZEND_NUM_ARGS() != 4 || zend_get_parameters_array_ex(4, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,6,CONVERT_INT_IN@*/
  arg1 = (int) zval_get_long(&args[0]);
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[3])) {
    arg4 = (char *) 0;
  } else {
    convert_to_string(&args[3]);
    arg4 = (char *) Z_STRVAL(args[3]);
  }
  /*@SWIG@*/;
  
  result = (int)PcAPI_cryptFile(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


static PHP_METHOD(libpcphp,PcAPI_isEncrypted) {
  PHP_FN(PcAPI_isEncrypted)(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}

static PHP_FUNCTION(PcAPI_isEncrypted) {
  char *arg1 = (char *) 0 ;
  zval args[1];
  int result;
  
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  /*@SWIG:/home/ccdev/bin/share/swig/4.1.0/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[0])) {
    arg1 = (char *) 0;
  } else {
    convert_to_string(&args[0]);
    arg1 = (char *) Z_STRVAL(args[0]);
  }
  /*@SWIG@*/;
  
  result = (int)PcAPI_isEncrypted((char const *)arg1);
  
  RETVAL_LONG(result);
  
fail:
  return;
}


/* class object handlers for pointer wrappers */
static zend_object_handlers swig_ptr_object_handlers;

/* Object Creation Method for pointer wrapping class */
static zend_object *swig_ptr_object_new(zend_class_entry *ce) {
  swig_object_wrapper *obj = (swig_object_wrapper*)zend_object_alloc(sizeof(swig_object_wrapper), ce);
  zend_object_std_init(&obj->std, ce);
  object_properties_init(&obj->std, ce);
  obj->std.handlers = &swig_ptr_object_handlers;
  obj->newobject = 0;
  return &obj->std;
}

/* Implement __toString equivalent, since that worked for the old-style resource wrapped pointers. */
#if PHP_MAJOR_VERSION < 8
static int swig_ptr_cast_object(zval *z, zval *retval, int type) {
#else
static int swig_ptr_cast_object(zend_object *zobj, zval *retval, int type) {
#endif
  if (type == IS_STRING) {
    char buf[80];
#if PHP_MAJOR_VERSION < 8
    swig_object_wrapper *obj = SWIG_Z_FETCH_OBJ_P(z);
#else
    swig_object_wrapper *obj = swig_php_fetch_object(zobj);
#endif
    sprintf(buf, "SWIGPointer(%p,owned=%d)", obj->ptr, obj->newobject);
    ZVAL_STRING(retval, buf);
    return SUCCESS;
  }
  return FAILURE;
}

/* end wrapper section */
/* arginfo subsection */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_initialize, 0, 2, MAY_BE_LONG)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_STRING,NULL)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_getSession, 0, 1, MAY_BE_LONG)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_STRING,NULL)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_encrypt, 0, 6, MAY_BE_LONG)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_LONG,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_LONG|MAY_BE_STRING,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg3,SWIG\\_p_unsigned_char,MAY_BE_NULL,NULL)
 ZEND_ARG_TYPE_MASK(0,arg4,MAY_BE_LONG,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg5,SWIG\\_p_unsigned_char,MAY_BE_NULL,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg6,SWIG\\_p_unsigned_int,MAY_BE_NULL,NULL)
ZEND_END_ARG_INFO()
#define swig_arginfo_PcAPI_decrypt swig_arginfo_PcAPI_encrypt
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_encrypt_name, 0, 6, MAY_BE_LONG)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_LONG,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_STRING,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg3,SWIG\\_p_unsigned_char,MAY_BE_NULL,NULL)
 ZEND_ARG_TYPE_MASK(0,arg4,MAY_BE_LONG,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg5,SWIG\\_p_unsigned_char,MAY_BE_NULL,NULL)
 ZEND_ARG_OBJ_TYPE_MASK(0,arg6,SWIG\\_p_unsigned_int,MAY_BE_NULL,NULL)
ZEND_END_ARG_INFO()
#define swig_arginfo_PcAPI_decrypt_name swig_arginfo_PcAPI_encrypt_name
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_enc_id, 0, 4, MAY_BE_NULL|MAY_BE_STRING)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_LONG,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_LONG|MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg3,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg4,MAY_BE_LONG,NULL)
ZEND_END_ARG_INFO()
#define swig_arginfo_PcAPI_dec_id swig_arginfo_PcAPI_enc_id
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_enc_nm, 0, 4, MAY_BE_NULL|MAY_BE_STRING)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_LONG,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg3,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg4,MAY_BE_LONG,NULL)
ZEND_END_ARG_INFO()
#define swig_arginfo_PcAPI_dec_nm swig_arginfo_PcAPI_enc_nm
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(swig_arginfo_PcAPI_cryptFile, 0, 4, MAY_BE_LONG)
 ZEND_ARG_TYPE_MASK(0,arg1,MAY_BE_LONG,NULL)
 ZEND_ARG_TYPE_MASK(0,arg2,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg3,MAY_BE_STRING,NULL)
 ZEND_ARG_TYPE_MASK(0,arg4,MAY_BE_STRING,NULL)
ZEND_END_ARG_INFO()
#define swig_arginfo_PcAPI_isEncrypted swig_arginfo_PcAPI_getSession


/* class entry subsection */


/* entry subsection */
/* Every non-class user visible function must have an entry here */
static const zend_function_entry module_libpcphp_functions[] = {
 PHP_FE(PcAPI_initialize,swig_arginfo_PcAPI_initialize)
 PHP_FE(PcAPI_getSession,swig_arginfo_PcAPI_getSession)
 PHP_FE(PcAPI_encrypt,swig_arginfo_PcAPI_encrypt)
 PHP_FE(PcAPI_decrypt,swig_arginfo_PcAPI_decrypt)
 PHP_FE(PcAPI_encrypt_name,swig_arginfo_PcAPI_encrypt_name)
 PHP_FE(PcAPI_decrypt_name,swig_arginfo_PcAPI_decrypt_name)
 PHP_FE(PcAPI_enc_id,swig_arginfo_PcAPI_enc_id)
 PHP_FE(PcAPI_dec_id,swig_arginfo_PcAPI_dec_id)
 PHP_FE(PcAPI_enc_nm,swig_arginfo_PcAPI_enc_nm)
 PHP_FE(PcAPI_dec_nm,swig_arginfo_PcAPI_dec_nm)
 PHP_FE(PcAPI_cryptFile,swig_arginfo_PcAPI_cryptFile)
 PHP_FE(PcAPI_isEncrypted,swig_arginfo_PcAPI_isEncrypted)
 ZEND_FE_END
};

static const zend_function_entry class_libpcphp_functions[] = {
 PHP_ME(libpcphp,PcAPI_initialize,swig_arginfo_PcAPI_initialize,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_getSession,swig_arginfo_PcAPI_getSession,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_encrypt,swig_arginfo_PcAPI_encrypt,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_decrypt,swig_arginfo_PcAPI_decrypt,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_encrypt_name,swig_arginfo_PcAPI_encrypt_name,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_decrypt_name,swig_arginfo_PcAPI_decrypt_name,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_enc_id,swig_arginfo_PcAPI_enc_id,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_dec_id,swig_arginfo_PcAPI_dec_id,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_enc_nm,swig_arginfo_PcAPI_enc_nm,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_dec_nm,swig_arginfo_PcAPI_dec_nm,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_cryptFile,swig_arginfo_PcAPI_cryptFile,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 PHP_ME(libpcphp,PcAPI_isEncrypted,swig_arginfo_PcAPI_isEncrypted,ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
 ZEND_FE_END
};

/* init section */
zend_module_entry libpcphp_module_entry = {
    STANDARD_MODULE_HEADER,
    "libpcphp",
    module_libpcphp_functions,
    PHP_MINIT(libpcphp),
    NULL, /* No MSHUTDOWN code */
    NULL, /* No RINIT code */
    NULL, /* No RSHUTDOWN code */
    NULL, /* No MINFO code */
    NO_VERSION_YET,
    STANDARD_MODULE_PROPERTIES
};

#ifdef __cplusplus
extern "C" {
#endif
SWIGEXPORT zend_module_entry *get_module(void) { return &libpcphp_module_entry; }
#ifdef __cplusplus
}
#endif

#define SWIG_php_minit PHP_MINIT_FUNCTION(libpcphp)

/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned statically to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif

#ifndef SWIG_INIT_CLIENT_DATA_TYPE
#define SWIG_INIT_CLIENT_DATA_TYPE void *
#endif

SWIGRUNTIME void
SWIG_InitializeModule(SWIG_INIT_CLIENT_DATA_TYPE clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int init;

  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }

  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    iter=module_head;
    do {
      if (iter==&swig_module) {
        /* Our module is already in the list, so there's nothing more to do. */
        return;
      }
      iter=iter->next;
    } while (iter!= module_head);

    /* otherwise we must add our module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }

  /* When multiple interpreters are used, a module could have already been initialized in
     a different interpreter, but not yet have a pointer in this interpreter.
     In this case, we do not want to continue adding types... everything should be
     set up already */
  if (init == 0) return;

  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %lu\n", (unsigned long)swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;

#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
#endif

    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
	type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }

    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {

      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
	if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
	if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
	  printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
	  cast->type = ret;
	  ret = 0;
	} else {
	  /* Check for casting already in the list */
	  swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
	  if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
	  if (!ocast) ret = 0;
	}
      }

      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
	printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
  printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;

  if (init_run) return;
  init_run = 1;

  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
            SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{ /* c-mode */
#endif
}
#endif


SWIG_php_minit {
  zend_class_entry SWIGUNUSED internal_ce;
  SWIG_InitializeModule((void*)&module_number);

  /* oinit subsection */
  INIT_CLASS_ENTRY(internal_ce, "libpcphp", class_libpcphp_functions);
  SWIG_Php_ce_libpcphp = zend_register_internal_class(&internal_ce);


  /* Register classes to represent non-class pointer types */
  swig_ptr_object_handlers = *zend_get_std_object_handlers();
  swig_ptr_object_handlers.offset = XtOffsetOf(swig_object_wrapper, std);
  swig_ptr_object_handlers.cast_object = swig_ptr_cast_object;
  INIT_CLASS_ENTRY(SWIG_Php_swig_wrapped_interface_ce, "SWIG\\wrapped", NULL);
  INIT_CLASS_ENTRY(internal_ce, "SWIG\\_p_unsigned_char", NULL);
  SWIG_Php_ce__p_unsigned_char = zend_register_internal_class(&internal_ce);
  SWIG_Php_ce__p_unsigned_char->create_object = swig_ptr_object_new;
  zend_do_implement_interface(SWIG_Php_ce__p_unsigned_char, &SWIG_Php_swig_wrapped_interface_ce);
  SWIG_TypeClientData(SWIGTYPE_p_unsigned_char,SWIG_Php_ce__p_unsigned_char);

  INIT_CLASS_ENTRY(internal_ce, "SWIG\\_p_unsigned_int", NULL);
  SWIG_Php_ce__p_unsigned_int = zend_register_internal_class(&internal_ce);
  SWIG_Php_ce__p_unsigned_int->create_object = swig_ptr_object_new;
  zend_do_implement_interface(SWIG_Php_ce__p_unsigned_int, &SWIG_Php_swig_wrapped_interface_ce);
  SWIG_TypeClientData(SWIGTYPE_p_unsigned_int,SWIG_Php_ce__p_unsigned_int);

  /* end oinit subsection */

  /* cinit subsection */
  /* end cinit subsection */

  return SUCCESS;
}

/* end init section */
