<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('libpcphp')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_libpcphp.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('libpcphp.so')) return;
    } else {
      if (!dl('libpcphp.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class libpcphp {
	static function PcAPI_initialize($info_file_path,$credentials_pw) {
		return PcAPI_initialize($info_file_path,$credentials_pw);
	}

	static function PcAPI_getSession($client_ip) {
		return PcAPI_getSession($client_ip);
	}

	static function PcAPI_encrypt($api_sid,$enc_col_id,$src,$src_len,$dst,$dst_len) {
		return PcAPI_encrypt($api_sid,$enc_col_id,$src,$src_len,$dst,$dst_len);
	}

	static function PcAPI_decrypt($api_sid,$enc_col_id,$src,$src_len,$dst,$dst_len) {
		return PcAPI_decrypt($api_sid,$enc_col_id,$src,$src_len,$dst,$dst_len);
	}

	static function PcAPI_encrypt_name($api_sid,$enc_col_name,$src,$src_len,$dst,$dst_len) {
		return PcAPI_encrypt_name($api_sid,$enc_col_name,$src,$src_len,$dst,$dst_len);
	}

	static function PcAPI_decrypt_name($api_sid,$enc_col_name,$src,$src_len,$dst,$dst_len) {
		return PcAPI_decrypt_name($api_sid,$enc_col_name,$src,$src_len,$dst,$dst_len);
	}

	static function PcAPI_enc_id($api_sid,$enc_col_id,$src,$src_len) {
		return PcAPI_enc_id($api_sid,$enc_col_id,$src,$src_len);
	}

	static function PcAPI_dec_id($api_sid,$enc_col_id,$src,$src_len) {
		return PcAPI_dec_id($api_sid,$enc_col_id,$src,$src_len);
	}

	static function PcAPI_enc_nm($api_sid,$enc_col_name,$src,$src_len) {
		return PcAPI_enc_nm($api_sid,$enc_col_name,$src,$src_len);
	}

	static function PcAPI_dec_nm($api_sid,$enc_col_name,$src,$src_len) {
		return PcAPI_dec_nm($api_sid,$enc_col_name,$src,$src_len);
	}

	static function PcAPI_cryptFile($api_sid,$parameters,$in_file_path,$out_file_path) {
		return PcAPI_cryptFile($api_sid,$parameters,$in_file_path,$out_file_path);
	}

	static function PcAPI_isEncrypted($file_name) {
		return PcAPI_isEncrypted($file_name);
	}
}

/* PHP Proxy Classes */

?>
