# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_libpcpython')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_libpcpython')
    _libpcpython = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libpcpython', [dirname(__file__)])
        except ImportError:
            import _libpcpython
            return _libpcpython
        try:
            _mod = imp.load_module('_libpcpython', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _libpcpython = swig_import_helper()
    del swig_import_helper
else:
    import _libpcpython
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def PcAPI_initialize(info_file_path, credentials_pw):
    return _libpcpython.PcAPI_initialize(info_file_path, credentials_pw)
PcAPI_initialize = _libpcpython.PcAPI_initialize

def PcAPI_getSession(client_ip):
    return _libpcpython.PcAPI_getSession(client_ip)
PcAPI_getSession = _libpcpython.PcAPI_getSession

def PcAPI_encrypt(api_sid, enc_col_id, src, src_len, dst, dst_len):
    return _libpcpython.PcAPI_encrypt(api_sid, enc_col_id, src, src_len, dst, dst_len)
PcAPI_encrypt = _libpcpython.PcAPI_encrypt

def PcAPI_decrypt(api_sid, enc_col_id, src, src_len, dst, dst_len):
    return _libpcpython.PcAPI_decrypt(api_sid, enc_col_id, src, src_len, dst, dst_len)
PcAPI_decrypt = _libpcpython.PcAPI_decrypt

def PcAPI_encrypt_name(api_sid, enc_col_name, src, src_len, dst, dst_len):
    return _libpcpython.PcAPI_encrypt_name(api_sid, enc_col_name, src, src_len, dst, dst_len)
PcAPI_encrypt_name = _libpcpython.PcAPI_encrypt_name

def PcAPI_decrypt_name(api_sid, enc_col_name, src, src_len, dst, dst_len):
    return _libpcpython.PcAPI_decrypt_name(api_sid, enc_col_name, src, src_len, dst, dst_len)
PcAPI_decrypt_name = _libpcpython.PcAPI_decrypt_name

def PcAPI_enc_id(api_sid, enc_col_id, src, src_len):
    return _libpcpython.PcAPI_enc_id(api_sid, enc_col_id, src, src_len)
PcAPI_enc_id = _libpcpython.PcAPI_enc_id

def PcAPI_dec_id(api_sid, enc_col_id, src, src_len):
    return _libpcpython.PcAPI_dec_id(api_sid, enc_col_id, src, src_len)
PcAPI_dec_id = _libpcpython.PcAPI_dec_id

def PcAPI_enc_nm(api_sid, enc_col_name, src, src_len):
    return _libpcpython.PcAPI_enc_nm(api_sid, enc_col_name, src, src_len)
PcAPI_enc_nm = _libpcpython.PcAPI_enc_nm

def PcAPI_dec_nm(api_sid, enc_col_name, src, src_len):
    return _libpcpython.PcAPI_dec_nm(api_sid, enc_col_name, src, src_len)
PcAPI_dec_nm = _libpcpython.PcAPI_dec_nm
# This file is compatible with both classic and new-style classes.


